# Hexo Configurationcrc32
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 你好可爱
subtitle: ""
description: "山水一程，三生有幸✨"
keywords: "Hexo,JavaScript,Vue,React,博客,你好可爱"
author: 你好可爱
language: zh-CN
timezone: ""

# abbrlink config
abbrlink:
  alg: crc32 #support crc16(default) and crc32
  rep: hex #support dec(default) and hex

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
# https://github.com/1405720461/1405720461.github.io
url: https://wjldarling.top/
permalink: posts/:abbrlink.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
# 指定不渲染某些页面
skip_render:
  [
    "box/collect/龙猫/**",
    "box/collect/One_Piece_gallery/**",
    "box/collect/particle_effects/**",
    "box/collect/love/**",
    "box/collect/12个动画/**",
    "box/collect/todolist/**",
    "box/collect/烟花绽放/**",
    "box/collect/响应式视差滚动相册/**",
    "box/collect/响应式时间轴/**",
    "box/collect/九宫格拼图游戏/**",
    "box/collect/太阳系运动/**",
    "box/collect/滑动登录注册页/**",
    "box/collect/Day-night-toggle-button-master/**",
    "box/collect/粘性球球/**",
    "box/collect/代码雨/**",
  ]

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ""

math:
  engine: "mathjax"
  mathjax:
    src: custom_mathjax_source
    config:
      # MathJax config

# 音乐插件
aplayer:
  meting: true
  asset_inject: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
# 首页显示文章数
index_generator:
  path: ""
  per_page: 12
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  - type: git
    repository:
    branch: main
  # - type: baidu_url_submitter
  # - type: git
  #   #repo改为repo: git@域名:/var/repo/hexo.git
  #   repo: git@43.249.9.21:/var/repo/hexo.git
  #   branch: main

# hexo-algolia(匹配标题)
# algolia:
#   applicationID: 78BL6ZB8EC
#   apiKey: 980d4a6ff043d026e5d9bf53e18c533a
#   indexName: index_1

# hexo-algoliasearch(可以匹配内容)
algolia:
  appId: ""
  apiKey: ""
  adminApiKey: ""
  chunkSize:
  indexName: ""
  fields:
    - content:strip:truncate,0,30000
    - excerpt:strip
    - gallery
    - permalink
    - photos
    - slug
    - tags
    - title

# 首页轮播图
# hexo-butterfly-swiper
# see https://akilar.top/posts/8e1264d1/
swiper:
  enable: true # 开关
  priority: 1 #过滤器优先权
  enable_page: / # 应用页面
  timemode: date #date/updated
  layout: # 挂载容器类型
    type: id
    name: recent-posts
    index: 0
  default_descr: 再怎么看我也不知道怎么描述它的啦！
  swiper_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.css #swiper css依赖
  swiper_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.js #swiper js依赖
  custom_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiperstyle.css # 适配主题样式补丁
  custom_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper_init.js # swiper初始化方法

# 本地搜索
search:
  path: search.xml
  field: post
  content: true

# Extensions
## Plugins: http://hexo.io/plugins/
#RSS订阅
plugin:
  - hexo-generator-feed
#Feed Atom
feed:
type: atom
path: atom.xml
limit: 20

# 站点地图
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# 主动推送百度，被百度收录
baidu_url_submit:
  count: 10 # 提交最新的10个链接
  host: # 百度站长平台中注册的域名
  token: # 秘钥，百度站长平台 > 推送接口 > 接口调用地址中token字段
  path: # 文本文档的地址， 新链接会保存在此文本文档里，不用改

nofollow:
  enable: false
  field: site
  exclude: ""

# 新版的搜索插件
plugins:
  - hexo-algoliasearch

# 追番模块
bangumi:
  enable: true
  vmid: 392071577
  path: /relaxation/bangumis/index.html
  title: "追番"
  quote: "追番追番！！！"
  show: 1
  lazyload: false

# # 豆瓣影院模块
# douban:
#   id: 271110737 # 你的豆瓣ID
#   builtin: false
#   movie:
#     path: /relaxation/movies
#     title: "影院"
#     comments: false
#     aside: true
#     quote: '<div class="wjl_rating">
#       <input value="star-1" name="star-radio" id="star-1" type="radio">
#       <label for="star-1">
#       <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z" pathLength="360"></path></svg>
#       </label>
#       <input value="star-1" name="star-radio" id="star-2" type="radio">
#       <label for="star-2">
#       <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z" pathLength="360"></path></svg>
#       </label>
#       <input value="star-1" name="star-radio" id="star-3" type="radio">
#       <label for="star-3">
#       <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z" pathLength="360"></path></svg>
#       </label>
#       <input value="star-1" name="star-radio" id="star-4" type="radio">
#       <label for="star-4">
#       <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z" pathLength="360"></path></svg>
#       </label>
#       <input value="star-1" name="star-radio" id="star-5" type="radio">
#       <label for="star-5">
#       <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z" pathLength="360"></path></svg>
#       </label>
#       </div>'
#   game:
#     path: /box/games
#     title: "游戏"
#     comments: false
#     aside: true
#     quote: '<div class="wjl_rating">
#       <input value="star-1" name="star-radio" id="star-1" type="radio">
#       <label for="star-1">
#       <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z" pathLength="360"></path></svg>
#       </label>
#       <input value="star-1" name="star-radio" id="star-2" type="radio">
#       <label for="star-2">
#       <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z" pathLength="360"></path></svg>
#       </label>
#       <input value="star-1" name="star-radio" id="star-3" type="radio">
#       <label for="star-3">
#       <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z" pathLength="360"></path></svg>
#       </label>
#       <input value="star-1" name="star-radio" id="star-4" type="radio">
#       <label for="star-4">
#       <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z" pathLength="360"></path></svg>
#       </label>
#       <input value="star-1" name="star-radio" id="star-5" type="radio">
#       <label for="star-5">
#       <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z" pathLength="360"></path></svg>
#       </label>
#       </div>'

#   timeout: 10000

# 小冰分类磁贴
magnet:
  enable: true
  priority: 2
  enable_page: /
  type: categories
  devide: 3
  display:
    - name: 前端
      display_name: 前端笔记
      icon: 🍡
    - name: 周记
      display_name: 每周点点滴滴
      icon: 📰
    - name: 电影
      display_name: 观影有感
      icon: 🎥
    - name: 读书
      display_name: 读书有感
      icon: 📖
    - name: 演示
      display_name: 案例演示笔记
      icon: 🍥
    - name: 奇奇怪怪
      display_name: 奇奇怪怪知识
      icon: 👻
    - name: 恋爱
      display_name: 恋爱日常分享
      icon: 🧡
    - name: AI
      display_name: AI 笔记
      icon: 🤖

  color_setting:
    text_color: black # 文字默认颜色
    text_hover_color: white # 文字鼠标悬浮颜色
    background_color: "#e9e9e9" # 文字背景默认颜色
    background_hover_color: var(--text-bg-hover) # 文字背景悬浮颜色
  layout:
    type: id
    name: recent-posts
    index: 0
  temple_html: '<div class="recent-post-item" style="width:100%;height: auto"><div id="catalog_magnet">${temple_html_item}</div></div>'
  plus_style: ""

#live2d模型配置
OhMyLive2d:
  enable: true
  CDN: /js/oh-my-live2d.js
  # CDN: https://registry.npmmirror.com/oh-my-live2d/latest/files
  # CDN: https://registry.npmmirror.com/oh-my-live2d/0.13/files/dist/index.min.js
  option:
    # importType: 'cubism2' #  导入类型, 默认使用全量导入: complete , 可选值: complete, cubism2, cubism5
    libraryUrls: # 自定义 Cubism SDK 外部资源地址
      complete: https://registry.npmmirror.com/oh-my-live2d/latest/files/lib/complete.js
      cubism2: https://registry.npmmirror.com/oh-my-live2d/latest/files/lib/cubism2.js
      cubism5: https://registry.npmmirror.com/oh-my-live2d/latest/files/lib/cubism5.js
    menus:
      items: |
        (defaultItems)=>{
          return [
            {
              id: 'change',
              title: '箴言',
              icon: 'icon-chat',
              onClick(oml2d) {
                oml2d.tipsMessage(getRandomQuote());
              }
            },
            defaultItems[2],
            defaultItems[0]
          ];
        }

    mobileDisplay: false # 是否在移动端显示
    models:
      - path: /live2d/Frieren/Frieren.model3.json
        motionPreloadStrategy: IDLE # 动作预加载策略 默认值: IDLE 可选值: ALL | IDLE | NONE
        position: [-30, 0]
        scale: 0.04
        stageStyle:
          width: 220
          height: 308
      - path: /live2d/兔兔/兔兔-阿米娅.model3.json
        position: [-30, 78] # 模型在舞台中的位置。 默认值: [0,0] [横坐标, 纵坐标]
        scale: 0.08 # 模型的缩放比例 默认值: 0.1
        stageStyle:
          height: 250
    parentElement: document.getElementById('oml2d') #为组件提供一个父元素，如果未指定则默认挂载到 body 中
    primaryColor: "var(--btn-bg)" # 主题色 支持变量
    sayHello: false # 是否在初始化阶段打印项目信息
    statusBar:
      restMessage: "兔兔休息中"
    tips:
      style:
        width: 220
        height: auto
        left: calc(50% + 25px)
        top: 0
        fontSize: 16px
      idleTips:
        interval: 60000
        message: |
          function(){
            return getRandomQuote()
          }

# 恋爱秘密
encrypt: # hexo-blog-encrypt
  abstract: 只有你和我才知道密码!
  message: 这里记录我和女朋友的一些事情哦，需要密码才能进入!
  tags:
    - { name: 恋爱, password: "wangjinglun" }
    - { name: 奇奇怪怪, password: "wjldarling.top" }
  theme: xray
  wrong_pass_message: 抱歉, 这个密码看着不太对, 请再试试.
  wrong_hash_message: 抱歉, 这个文章不能被校验, 不过您还是能看看解密后的内容.
